FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MTAA_APP_backend

Backend pre workout aplikáciu vytváranú na predmete MTAA na FIIT STU.
            
## Authentification [/auth]   
### Create User [POST /auth/register]

+ Request (application/json)

        {
        "username": "John Doe",
        "email": "john@example.com",
        "password": "securepassword123"
        }

+ Response 201 (application/json)

        {
        "message": "User added successfully"
        }

+ Response 409 (application/json)

        {
        "message": "Email already exists"
        }
        
+ Response 400 (application/json)        
        
        {
        "message": "Some information missing"
        } 

### Login [POST /auth/login]

+ Request (application/json)

        {
        "email": "john@example.com",
        "password": "securepassword123"
        }

+ Response 200 (application/json)

        {
        "token": "jwt_token",
        "user_id": 1
        }

+ Response 401 (application/json)

        {
        "msg": "Bad email or password"
        }

### Get Current User [GET /auth/getuser]
+ Request
    + Headers
    
            Authorization: Bearer jwt_token

+ Response 200 (application/json)

        {
        "user_id": 1,
        "user_name": "John Doe",
        "email": "john@example.com"
        }


## User management [/user]
### Change Username [PATCH /user/change/username]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body 

            {
            "username": "new_username"
            }

+ Response 200 (application/json)

        {
        "message": "Username changed"
        }

+ Response 400 (application/json)

        {
        "message": "No username entered"
        }

### Change Password [PATCH /user/change/password]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token
    
    + Body
    
            {
            "password": "new_password"
            }

+ Response 200 (application/json)

        {
        "message": "Password changed"
        }

+ Response 400 (application/json)

        {
        "message": "No password entered"
        }

### Upload Profile Photo [PATCH /user/change/photo]

+ Request (image/jpg)
    + Headers
    
            Authorization: Bearer jwt_token
    
    + Body
    
            (binary image data)

+ Response 201 (application/json)

        {
        "msg": "File uploaded successfully!"
        }

+ Response 400 (application/json)

        {
        "error": "No file provided"
        }

### Get Profile Photo [GET /user/get/photo]

+ Request
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (image/jpg)

        (binary image content)

+ Response 404 (application/json)

        {
        "error": "No profile picture provided"
        }

### Delete User Account [DELETE /user/change/delete]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "password": "securepassword123"
            }

+ Response 200 (application/json)

        {
        "error": "User deleted"
        }

+ Response 401 (application/json)

        {
        "error": "Incorrect password"
        }

+ Response 401 (application/json)

        {
        "error": "User doesn't exist"
        }


## Workout [/workout]
### Create Workout [POST/workout/createWorkout]
+ workout_name (string) - Názov nového workoutu
+ workout_start (Datetime) - Dátum a čas kedy workout začal vo formáte dd-mm-yyyy HH:MM:SS
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_name": "TEst4",
                "workout_start": "21-4-2005 10:11:12"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Workout created successfully",
                "workout_id": 1
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

### Upload WorkoutData [POST /workout/uploadData]
+ workout_id (int) - Id workoutu ktorému patria nové záznamy
+ samples (array) - zoznam nových záznamov
+ sample_time (Datetime) - Dátum a čas namerania záznamu vo formáte dd-mm-yyyy HH:MM:SS
+ position_lat (float) - Zemepisná šírka záznamu
+ position_lon (float) - Zemepisná dĺžka záznamu
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "samples": [
                    {
                        "sample_time": "21-4-2024 12:22:44",
                        "position_lat": 23.46,
                        "position_lon": 10.1
                    },
                    {
                        "sample_time": "22-4-2024 12:22:45",
                        "position_lat": 23.46,
                        "position_lon": 10.431
                    }
                ]
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Samples added successfully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

### Add Participant [PUT /workout/addParticipant]
+ workout_id (int) - Id workoutu ku ktorému sa pridáva nový účastník
+ participant_id (int) - Id nového účastníka
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "participant_id": 2
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Participant added succefully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "User doesn't exist"
            }

+ Response 403 (application/json)

    + Body

            {
                "message": "New participant is not a friend"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 403 (application/json)

    + Body

            {
                "message": "Participant already exist"
            }

### Upadate Participant Data [PUT /workout/updateParticipantData]
+ workout_id (int): Id workoutu ktorému sa nastavujú údaje
+ total_distance (float): Celková vzdialenosť, ktorú účastník prešiel
+ avg_speed (float): Priemerná rýchlosť, ktorou účastník išiel
+ max_speed (float): Najvyššia rýchlosť, ktorou účastník išiel
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

        {
            "workout_id": 1,
            "total_distance": 61.3,
            "avg_speed": 5.1,
            "max_speed": 10
        }

+ Response 200 (application/json)

    + Body

            {
                "message": "Participant updated succefully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Get Workout List [GET /workout/getList]

+ Response 200 (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workouts": [
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 1,
                        "workout_name": "TEst1",
                        "workout_start": "Sun, 21 Apr 2024 00:00:00 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 2,
                        "workout_name": "TEst2",
                        "workout_start": "Sun, 21 Apr 2024 00:00:00 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 3,
                        "workout_name": "TEst3",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 4,
                        "workout_name": "TEst4",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 5,
                        "workout_name": "TEst5",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 6,
                        "workout_name": "TEst6",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    }
                ]
            }

### Get Workout Data [GET /workout/getData]
+ workout_id (int): Id workoutu z ktorého si pýtame záznamy
+ from_sampe (int): Id od ktorého sa posielajú záznamy
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "from_sampe": 0
            }

+ Response 200 (application/json)

    + Body
    
            {
                "samples": [
                    {
                        "position_lat": 23.46,
                        "position_lon": 10.1,
                        "sample_id": 1,
                        "sample_time": "Sun, 21 Apr 2024 00:00:00 GMT",
                        "user_id": 1,
                        "workout_id": 1
                    },
                    {
                        "position_lat": 23.46,
                        "position_lon": 10.431,
                        "sample_id": 2,
                        "sample_time": "Mon, 22 Apr 2024 00:00:00 GMT",
                        "user_id": 1,
                        "workout_id": 1
                    }
                ]
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Delete Workout [DELETE /workout/deleteWorkout]
+ workout_id (int): Id workoutu, ktorý chceme zmazať
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token
    
    + Body

            {
                "workout_id": 1
            }

+ Response 200 (application/json)

    + Body

            {
                {
                    "message": "Workout deleted successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Share Workout [PUT /workout/shareWorkout]
+ workout_id (int): Id workout, ktorý bude zdielaný
+ shared_user_id (int): Id používateľa, s ktorým chceme zdieľať workout
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "shared_user_id": 2
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                {
                    "message": "Workout shared successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Workout is alredy shared"
            }

### Unshare Workout [DELETE /workout/unshareWorkout]
+ workout_id (int): Id workout, ktorý chceme prestať zdieľať
+ shared_user_id (int): Id používateľa, s ktorým chceme prestať zdieľať workout
+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "shared_user_id": 2
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                {
                    "message": "Workout unshared successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Workout isn't shared"
            }
            
            
## Friend requests [/friends/request]
### Create Friend Request [POST /friends/request/create]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "email": "friend@example.com"
            }

+ Response 201 (application/json)

        {
        "message": "Friend request made"
        }

+ Response 409 (application/json)

        {
        "message": "Request made before or users already friends"
        }

+ Response 404 (application/json)

        {
        "message": "User with entered email doesn't exist"
        }

+ Response 409 (application/json)

        {
        "message": "User's own email entered"
        }

### Get Friend Request List [GET /friends/request/get]

+ Request
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (application/json)

        [
            {
            "user_id": 2,
            "user_name": "alice",
            "email": "alice@example.com"
            },
            {
            "user_id": 3,
            "user_name": "bob",
            "email": "bob@example.com"
            }
        ]

### Accept Friend Request [PATCH /friends/request/accept]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 201 (application/json)

        {
        "message": "Friend request accepted"
        }

+ Response 404 (application/json)

        {
        "message": "Friend request doesn't exist"
        }

### Reject Friend Request [DELETE /friends/request/reject]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "friend_id": 2
            }

+ Response 200 (application/json)

        {
        "message": "Friend request removed"
        }

+ Response 404 (application/json)

        {
        "message": "Friend request doesn't exist"
        }


## Friends [/friends]

### Get Friend list [GET /friends/get]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (application/json)

        [
            {
            "user_id": 2,
            "user_name": "alice",
            "email": "alice@example.com"
            },
            {
            "user_id": 3,
            "user_name": "bob",
            "email": "bob@example.com"
            }
        ]

### Remove Friend [DELETE /friends/remove]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "friend_id": 2
            }

+ Response 200 (application/json)

        {
        "message": "Friend removed"
        }

+ Response 404 (application/json)

        {
        "message": "Friend doesn't exist"
        }

### Get Friend Profile [GET /friends/getuser]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 200 (application/json)

        {
        "user_id": 2,
        "user_name": "alice",
        "email": "alice@example.com"
        }

+ Response 404 (application/json)

        {
        "message": "User not in friends"
        }

### Get Friend Profile Photo [GET /friends/getphoto]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 200 (image/jpg)

        (binary image content)

+ Response 404 (application/json)

        {
        "error": "No profile picture provided"
        }

+ Response 404 (application/json)

        {
        "message": "User not in friends"
        }