FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MTAA_APP_backend

Backend pre workout aplikáciu vytváranú na predmete MTAA na FIIT STU.
            
## Authentification [/auth]   
### Create User [POST /auth/register]

+ Request (application/json)
    + Attributes

        + username: John Doe (string) - User's chosen username
        + email: john@example.com (string) - User's email address
        + password: securepassword123 (string) - User's password
        
    + Body

            {
            "username": "John Doe",
            "email": "john@example.com",
            "password": "securepassword123"
            }

+ Response 201 (application/json)
    + Attributes

        + message: User added successfully (string)- Confirmation message
    
    + Body    
        
            {
            "message": "User added successfully"
            }

+ Response 409 (application/json)
    + Attributes

        + message: Email already exists (string)- Error message
    
    + Body    
        
            {
            "message": "Email already exists"
            }
            
+ Response 400 (application/json)        
    + Attributes

        + message: Some information missing (string)- Error message

    + Body
    
            {
            "message": "Some information missing"
            } 

### Login [POST /auth/login]

+ Request (application/json)
    + Attributes

        + email: john@example.com (string) - User's email address
        + password: securepassword123 (string) - User's password
        
    + Body

            {
            "email": "john@example.com",
            "password": "securepassword123"
            }

+ Response 200 (application/json)
    + Attributes

        + token: "jwt_token" (string) - JWT token for authentification 
        + user_id: 1 (string) - User's id
        
    + Body

            {
            "token": "jwt_token",
            "user_id": 1
            }

+ Response 401 (application/json)
    + Attributes

        + message: Bad email or password (string)- Error message.

    + Body
    
            {
            "message": "Bad email or password"
            }

### Get Current User [GET /auth/getuser]
+ Request
    + Headers
    
            Authorization: Bearer jwt_token

+ Response 200 (application/json)
    + Attributes

        + username: John Doe (string) - User's chosen username
        + email: john@example.com (string) - User's email address
        + password: securepassword123 (string) - User's password

    + Body

            {
            "user_id": 1,
            "user_name": "John Doe",
            "email": "john@example.com"
            }


## User management [/user]
### Change Username [PATCH /user/change/username]

+ Request (application/json)
    + Attributes

        + username: new_username (string) - User's new username
        
    + Headers

            Authorization: Bearer jwt_token

    + Body 

            {
            "username": "new_username"
            }

+ Response 200 (application/json)
    + Attributes

        + message: Username changed (string)- Confirmation message

    + Body

            {
            "message": "Username changed"
            }

+ Response 400 (application/json)
    + Attributes

        + message: No username entered (string)- Error message

    + Body

            {
            "message": "No username entered"
            }

### Change Password [PATCH /user/change/password]

+ Request (application/json)
   + Attributes

        + password: new_password (string)- User's new password
   
    + Headers

            Authorization: Bearer jwt_token
    
    + Body
    
            {
            "password": "new_password"
            }

+ Response 200 (application/json)
    + Attributes

        + message: Password changed (string)- Confirmation message

    + Body

            {
            "message": "Password changed"
            }

+ Response 400 (application/json)
    + Attributes

        + message: No password entered (string)- Error message

    + Body
    
            {
            "message": "No password entered"
            }

### Upload Profile Photo [PATCH /user/change/photo]

+ Request (image/jpg)
    + Headers
    
            Authorization: Bearer jwt_token
    
    + Body
    
            (binary image data)

+ Response 201 (application/json)
    + Attributes

        + message: File uploaded successfully! (string)- Confirmation message

    + Body
    
            {
            "msg": "File uploaded successfully!"
            }

+ Response 400 (application/json)
    + Attributes

        + message: No file provided (string)- Error message

    + Body
    
            {
            "error": "No file provided"
            }

### Get Profile Photo [GET /user/get/photo]

+ Request
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (image/jpg)

        (binary image content)

+ Response 404 (application/json)
    + Attributes

        + message: No profile picture provided (string)- Error message

    + Body

            {
            "error": "No profile picture provided"
            }

### Delete User Account [DELETE /user/change/delete]

+ Request (application/json)
    + Attributes

        + password: securepassword123 (string)- User's password

    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "password": "securepassword123"
            }

+ Response 200 (application/json)
    + Attributes

        + message: User deleted (string)- Confirmation message

    + Body

            {
            "error": "User deleted"
            }

+ Response 401 (application/json)
    + Attributes

        + message: Incorrect password (string)- Error message

    + Body

            {
            "error": "Incorrect password"
            }

+ Response 401 (application/json)
    + Attributes

        + message: User doesn't exist (string)- Error message

    + Body

            {
            "error": "User doesn't exist"
            }


## Workout [/workout]
### Create Workout [POST/workout/createWorkout]
+ Request (application/json)
    + Attributes
        + workout_name: (string) - Názov nového workoutu
        + workout_start: (string) - Dátum a čas kedy workout začal vo formáte dd-mm-yyyy HH:MM:SS
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_name": "TEst4",
                "workout_start": "21-4-2005 10:11:12"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Workout created successfully",
                "workout_id": 1
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

### Upload WorkoutData [POST /workout/uploadData]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu ktorému patria nové záznamy
        + sample_time: (string) - Dátum a čas namerania záznamu vo formáte dd-mm-yyyy HH:MM:SS
        + position_lat: (number) - Zemepisná šírka záznamu
        + position_lon: (number) - Zemepisná dĺžka záznamu
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "samples": [
                    {
                        "sample_time": "21-4-2024 12:22:44",
                        "position_lat": 23.46,
                        "position_lon": 10.1
                    },
                    {
                        "sample_time": "22-4-2024 12:22:45",
                        "position_lat": 23.46,
                        "position_lon": 10.431
                    }
                ]
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Samples added successfully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

### Add Participant [PUT /workout/addParticipant]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu ku ktorému sa pridáva nový účastník
        + participant_id: (number) - Id nového účastníka
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "participant_id": 2
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "Participant added succefully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "User doesn't exist"
            }

+ Response 403 (application/json)

    + Body

            {
                "message": "New participant is not a friend"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 403 (application/json)

    + Body

            {
                "message": "Participant already exist"
            }

### Upadate Participant Data [PUT /workout/updateParticipantData]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu ktorému sa nastavujú údaje
        + total_distance: (number) - Celková vzdialenosť, ktorú účastník prešiel
        + avg_speed: (number) - Priemerná rýchlosť, ktorou účastník išiel
        + max_speed: (number) - Najvyššia rýchlosť, ktorou účastník išiel
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "workout_id": 1,
            "total_distance": 61.3,
            "avg_speed": 5.1,
            "max_speed": 10
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Participant updated succefully"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Get Workout List [GET /workout/getList]

+ Response 200 (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu
        + workout_name: (string) - Meno workoutu
        + workout_start: (string) - Dátum a čas kedy začal workout
        + user_id: (number) - Id používateľa pre ktorému patria údaje
        + total_distance: (number) - Celková vzdialenosť prejdená účastníkom
        + avg_speed: (number) - Priemerná rýchlosť účastníka
        + max_speed: (number) - Največšia rýchlosť účastníka
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workouts": [
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 1,
                        "workout_name": "TEst1",
                        "workout_start": "Sun, 21 Apr 2024 00:00:00 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 2,
                        "workout_name": "TEst2",
                        "workout_start": "Sun, 21 Apr 2024 00:00:00 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 3,
                        "workout_name": "TEst3",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 4,
                        "workout_name": "TEst4",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 5,
                        "workout_name": "TEst5",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    },
                    {
                        "avg_speed": null,
                        "max_speed": null,
                        "total_distance": null,
                        "user_id": 1,
                        "workout_id": 6,
                        "workout_name": "TEst6",
                        "workout_start": "Thu, 21 Apr 2005 10:11:12 GMT"
                    }
                ]
            }

### Get Workout Data [GET /workout/getData]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu z ktorého si pýtame záznamy
        + from_sampe: (number) - Id od ktorého sa posielajú záznamy
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "from_sampe": 0
            }

+ Response 200 (application/json)

    + Attributes
        + workout_id: (number) - Id workoutu, ktorému patrí záznam
        + user_id: (number) - Id účastníku, ktorému patrí záznam
        + sample_id: (number) - Id záznamu
        + sample_time: (string) - Dátum a čas namerania záznamu vo formáte dd-mm-yyyy HH:MM:SS
        + position_lat: (number) - Zemepisná šírka záznamu
        + position_lon: (number) - Zemepisná dĺžka záznamu
        
    + Body
    
            {
                "samples": [
                    {
                        "position_lat": 23.46,
                        "position_lon": 10.1,
                        "sample_id": 1,
                        "sample_time": "Sun, 21 Apr 2024 00:00:00 GMT",
                        "user_id": 1,
                        "workout_id": 1
                    },
                    {
                        "position_lat": 23.46,
                        "position_lon": 10.431,
                        "sample_id": 2,
                        "sample_time": "Mon, 22 Apr 2024 00:00:00 GMT",
                        "user_id": 1,
                        "workout_id": 1
                    }
                ]
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Delete Workout [DELETE /workout/deleteWorkout]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workoutu, ktorý chceme zmazať
    + Headers

            Authorization: Bearer jwt_token
    
    + Body

            {
                "workout_id": 1
            }

+ Response 200 (application/json)

    + Body

            {
                {
                    "message": "Workout deleted successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

### Share Workout [PUT /workout/shareWorkout]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workout, ktorý bude zdielaný
        + shared_user_id: (number) - Id používateľa, s ktorým chceme zdieľať workout
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "shared_user_id": 2
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                {
                    "message": "Workout shared successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Workout is alredy shared"
            }

### Unshare Workout [DELETE /workout/unshareWorkout]
+ Request (application/json)
    + Attributes
        + workout_id: (number) - Id workout, ktorý chceme prestať zdieľať
        + shared_user_id: (number) - Id používateľa, s ktorým chceme prestať zdieľať workout
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
                "workout_id": 1,
                "shared_user_id": 2
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                {
                    "message": "Workout unshared successfully"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Wrong data type"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Workout doesn't exist"
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "Workout isn't shared"
            }
            
            
## Friend requests [/friends/request]
### Create Friend Request [POST /friends/request/create]

+ Request (application/json)
    + Attributes

        + email: friend@example.com (string) - Friend's email address
        
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "email": "friend@example.com"
            }

+ Response 201 (application/json)
    + Attributes

        + message: Friend request made (string) - Confirmation message
        
    + Body
    
            {
            "message": "Friend request made"
            }

+ Response 409 (application/json)
    + Attributes

        + message: Request made before or users already friends (string) - Error message
        
    + Body

            {
            "message": "Request made before or users already friends"
            }

+ Response 404 (application/json)
    + Attributes

        + message: User with entered email doesn't exist (string) - Error message
        
    + Body

        {
        "message": "User with entered email doesn't exist"
        }

+ Response 409 (application/json)
    + Attributes

        + message: User's own email entered (string) - Error message

    + Body

        {
        "message": "User's own email entered"
        }

d
### Get Friend Request List [GET /friends/request/get]

+ Request
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (application/json)
    + Attributes

        + user_id: 2 (number) - User's id
        + user_name: alice (string) - User's name
        + email: alice@example.com (string) - User's email

    + Body

            [
                {
                "user_id": 2,
                "user_name": "alice",
                "email": "alice@example.com"
                },
                {
                "user_id": 3,
                "user_name": "bob",
                "email": "bob@example.com"
                }
            ]

### Accept Friend Request [PATCH /friends/request/accept]
+ Request (application/json)
    + Attributes

        + friend_id: 2 (number) - Friend's id
        
    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 201 (application/json)
    + Attributes
        + message: Friend request accepted (string) - Confirmation message
        
    + Body

            {
            "message": "Friend request accepted"
            }

+ Response 404 (application/json)
    + Attributes
        + message: Friend request doesn't exist (string) - Error message
        
    + Body

            {
            "message": "Friend request doesn't exist"
            }

### Reject Friend Request [DELETE /friends/request/reject]

+ Request (application/json)
    + Attributes

        + friend_id: 2 (number) - Friend's id
        
    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "friend_id": 2
            }

+ Response 200 (application/json)
    + Attributes
        + message: Friend request removed (string) - Confirmation message
        
    + Body

            {
            "message": "Friend request removed"
            }

+ Response 404 (application/json)
    + Attributes
        + message: Friend request doesn't exist (string) - Error message
        
    + Body

            {
            "message": "Friend request doesn't exist"
            }


## Friends [/friends]

### Get Friend list [GET /friends/get]

+ Request (application/json)
    + Headers

            Authorization: Bearer jwt_token

+ Response 200 (application/json)
    + Attributes

        + user_id: 2 (number) - User's id
        + user_name: alice (string) - User's name
        + email: alice@example.com (string) - User's email
        
    + Body

            [
                {
                "user_id": 2,
                "user_name": "alice",
                "email": "alice@example.com"
                },
                {
                "user_id": 3,
                "user_name": "bob",
                "email": "bob@example.com"
                }
            ]

### Remove Friend [DELETE /friends/remove]

+ Request (application/json)
    + Attributes

        + friend_id: 2 (number) - Friends's id

    + Headers

            Authorization: Bearer jwt_token

    + Body

            {
            "friend_id": 2
            }

+ Response 200 (application/json)
    + Attributes

        + message: Friend removed (string) - Confirmation message
        
    + Body

            {
            "message": "Friend removed"
            }

+ Response 404 (application/json)
    + Attributes

        + message: Friend doesn't exist (string) - Error message
        
    + Body

            {
            "message": "Friend doesn't exist"
            }

### Get Friend Profile [POST /friends/getuser]

+ Request (application/json)
    + Attributes

        + friend_id: 2 (number) - Friends's id

    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 200 (application/json)
    + Attributes

        + user_id: 2 (number) - User's id
        + user_name: alice (string) - User's name
        + email: alice@example.com (string) - User's email
     
    + Body

            {
            "user_id": 2,
            "user_name": "alice",
            "email": "alice@example.com"
            }

+ Response 404 (application/json)
    + Attributes

        + message: User not in friends (string) - Error message
        
    + Body

            {
            "message": "User not in friends"
            }

### Get Friend Profile Photo [POST /friends/getphoto]

+ Request (application/json)
    + Attributes

        + friend_id: 2 (number) - Friend's id

    + Headers

            Authorization: Bearer jwt_token

    + Body
    
            {
            "friend_id": 2
            }

+ Response 200 (image/jpg)

        (binary image content)

+ Response 404 (application/json)
    + Attributes

        + message: No profile picture provided (string) - Error message
    + Body
    
            {
            "error": "No profile picture provided"
            }

+ Response 404 (application/json)
    + Attributes

        + message: User not in friends (string) - Error message
    + Body
    
            {
            "message": "User not in friends"
            }